"""add authentication tables and update agency_users

Revision ID: 409416e0fc04
Revises: f0219e1e9816
Create Date: 2025-12-31 12:39:16.362913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409416e0fc04'
down_revision: Union[str, Sequence[str], None] = 'f0219e1e9816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_users', sa.Column('auth_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_agency_users_auth_user_id'), 'agency_users', ['auth_user_id'], unique=False)
    op.create_foreign_key(None, 'agency_users', 'auth_users', ['auth_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agency_users', type_='foreignkey')
    op.drop_index(op.f('ix_agency_users_auth_user_id'), table_name='agency_users')
    op.drop_column('agency_users', 'auth_user_id')
    # ### end Alembic commands ###
