"""changning models

Revision ID: 6a6f38e81ebc
Revises: 315ee77238a6
Create Date: 2026-01-07 00:50:50.700129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6f38e81ebc'
down_revision: Union[str, Sequence[str], None] = '315ee77238a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verification_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('email_verification_tokens', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
